### ISSUE TITLE
Re-roll button

### ISSUE THREAD

**Issue by luahj2** [ZeldaFan0225/AI_Horde_Discord#27]
**Is your feature request related to a problem? Please describe.**

A re-roll button next to the "Delete this message" would be pretty useful imo.

**Describe the solution you'd like**

the re-roll button should run the image generation again but with a different seed.

**Describe alternatives you've considered**

not sure about alternatives.

**Additional context**

**Comment by Efreak** [comment]
I've tried implementing similar functionality (updating /userinfo output), but I have no idea how to get the command parameters from a message in discord.js (my only exposure to discord.js is via the bot, which doesn't seem to have any functionality that does this, and I can't figure out an appropriate set of search terms to figure this out online).

**Comment by ZeldaFan0225** [comment]
After debating on whether this should be implemented I've decided not add this functionality, for the reason that Discord added actually usable command views where you can copy the usage, paste it and run the command again. This will also not delete the previously generated image by sending a new message.
