### ISSUE TITLE
Support for LoRas in style

### ISSUE THREAD

**Issue by db0** [ZeldaFan0225/AI_Horde_Discord#32]
We recently added support for LoRas. I have created some styles which allow them. Would be nice to allow the bot to utilize them

https://github.com/Haidra-Org/AI-Horde-Styles/blob/main/styles.json

**Comment by ZeldaFan0225** [comment]
how should i implement something i have no idea about what it does? a short explanation or what LoRas is or what it does would be nice

**Comment by db0** [comment]
LoRas as basically model diffs/patches. They allow a model to go in a specific direction by adding ~100Mb of extra data. See: https://aituts.com/stable-diffusion-lora/

The way it works in the payload is that there's a "loras" key in which you can send a list of dicts. (Check the `ModelPayloadLorasStable` model in the API).

For the purpose of this, all you need to do is the style contains a "loras" key, you add it to the payload "params" key, like so https://github.com/Haidra-Org/mastodon-ai-horde-generate/blob/02eb2d6c66279827de81f8c7f413fd6359b031f7/bot/notifications.py#L92

**Comment by ZeldaFan0225** [comment]
ill see what i can do thanks for the clearification

**Comment by ZeldaFan0225** [comment]
i added this to both generate and advanced generate
