### ISSUE TITLE
Support for categories in styles

### ISSUE THREAD

**Issue by db0** [ZeldaFan0225/AI_Horde_Discord#33]
Along with styles, I also have categories which support multiple styles https://github.com/Haidra-Org/AI-Horde-Styles/blob/main/categories.json

Should be possible to specify a style or a category for "style". When a category is specified, pick 4 random styles from that category.

Some categories are nested. When used, they should expand to all the nested styles in all cateogires.

Here's my python implementation of this for my mastodon bot in case it helps: https://github.com/Haidra-Org/mastodon-ai-horde-generate/blob/02eb2d6c66279827de81f8c7f413fd6359b031f7/bot/notifications.py#L239

**Comment by ZeldaFan0225** [comment]
added in https://github.com/ZeldaFan0225/AI_Horde_Discord/commit/b1d66c42e535eaf346c01c6d11febbf2b62f90a3
