### ISSUE TITLE
Add switch to /userinfo to make it ephemeral

### ISSUE THREAD

**Issue by db0** [ZeldaFan0225/AI_Horde_Discord#34]
Currently /userinfo is always displayed for everyone, which is not always necessary. For example when as a mod I want to discover someone's account so I can check their suspicion etc.

Request: Add a bool which will turn the /userinfo results ephemeral.

**Comment by ZeldaFan0225** [comment]
i don't see how this is neccessary since theres a delete button on the message so if you don't want everybody to see it just delete it

**Comment by db0** [comment]
Well, it still shows up even for a bit, so it can get in the way of flowing discussions and people have plenty of time to notice it.

**Comment by ZeldaFan0225** [comment]
added in https://github.com/ZeldaFan0225/AI_Horde_Discord/commit/c479ace6d11d9c6825ca92b7543cb5b4c45a4102
