### ISSUE TITLE
Feature request: Add support for Lora inject_trigger field in styles

### ISSUE THREAD

**Issue by Efreak** [ZeldaFan0225/AI_Horde_Discord#40]
Please add support for Lora triggers (inject_trigger field takes a string).
- If you intend to fetch the list of triggers from Civitai (unnecessary imo, see next part), it should have *any* and *all* added to the list (these tell the worker to add a random trigger or to add all triggers to the prompt).

Mostly I'd like support added for the styles (I don't much care about people generating with commands, they can figure out triggers themselves; I want styles with multiple-trigger loras to be able to pick a random trigger from those available).

**Comment by ZeldaFan0225** [comment]
this is already possible as the bot passes the exact loras array from the style data to the api, so it will pass on any `inject_trigger` in the styles json
