### ISSUE TITLE
Feature request: Textual Inversion support

### ISSUE THREAD

**Issue by Efreak** [ZeldaFan0225/AI_Horde_Discord#41]
Horde now supports all TIs on Civitai, would be nice to have support for them.

The format is as follows, all that's required is the name field (limit is unmentioned, the name is the Civitai id or fuzzy matching, just like loras):

```json
tis: [
  {
    "name": "str",
    "inject_ti": "prompt|negprompt",
    "strength":0.55
  }
]
```

Recommendation: if the user selects a TI but doesn't inject it in the prompt (no instance of `embedding:`), set inject_ti to "prompt".

Suggestion: allow specifying multiple TIs with a comma-separated list. People really like certain negative embeddings, and it would be nice to be able to use multiple. If autocomplete is implemented like it is for Loras and if possible, allow completion after the comma to add another TI

For styles, I intend to use the exact same syntax as the API (shown above). If you choose not to implement TIs, please at least pass the ti object through when using styles.

**Comment by ZeldaFan0225** [comment]
i added something in the latest commit please see if it checks your feature request
