### ISSUE TITLE
Feature request: allow blacklist to be a regex

### ISSUE THREAD

**Issue by Efreak** [ZeldaFan0225/AI_Horde_Discord#42]
I'd like to blacklist certain words without it mattering whether or not they're using exact case or doubling letters or adding accents. The easiest way to do this is to allow regexes in the blacklist. I've implemented this like so:

```typescript
if(ctx.client.config.advanced_generate?.blacklisted_regexes?.some(w => new RegExp(w,'i').test(prompt.normalize("NFD").replace(/[\u0300-\u036f]/g, "")))) return ctx.error({error: "Your prompt included one or more blacklisted words"})
```

I tried adding the regex directly in the config, but couldn't figure out how to add a regex in the schema in types.ts (stuff I found online didn't work), but this also just seems easier.

This can also control if certain words are only allowed in positive or negative prompt: "sad.*?###|###.*?happy" to disallow sad images.

**Comment by ZeldaFan0225** [comment]
the input of slash commands is already kinda normalized, 

![image](https://github.com/ZeldaFan0225/AI_Horde_Discord/assets/78901316/e5062256-779b-4f5a-b0be-6b915344e817)

it already gives it as plaintext or rather handles it as plaintext

**Comment by ZeldaFan0225** [comment]
this has been implemented
