### ISSUE TITLE
FR: Upscale command

### ISSUE THREAD

**Issue by Efreak** [ZeldaFan0225/AI_Horde_Discord#49]
I intended to implement this myself, and still plan to eventually if it's not done.

**Comment by ZeldaFan0225** [comment]
some context would be helpful e.g. how only upscaling can be done via the horde using which endpoint

**Comment by ZeldaFan0225** [comment]
Will not become its own command but I added the upscaling and other interrogation methods to the /interrogate command in [this commit](https://github.com/ZeldaFan0225/AI_Horde_Discord/commit/67fb3b12235db00225751b5d2246b7c33e258046)
